export const MAIN_SET_MESSAGE = 'MAIN_SET_MESSAGE'
export const MAIN_SET_FETCHING = 'MAIN_SET_FETCHING'

export const CATEGORIES_SET_DATA = 'CATEGORIES_SET_DATA'
export const PRODUCTS_SET_DATA = 'PRODUCTS_SET_DATA'
export const ROLES_SET_DATA = 'ROLES_SET_DATA'
export const ADMIN_HOUSE_TYPES_SET_DATA = 'ADMIN_HOUSE_TYPES_SET_DATA'
export const ADMIN_CUSTOM_FEE_TYPES_SET_DATA = 'ADMIN_CUSTOM_FEE_TYPES_SET_DATA'
export const OPERATING_COMPANIES_SET_DATA = 'OPERATING_COMPANIES_SET_DATA'
export const ADMIN_USERS_SET_DATA = 'ADMIN_USERS_SET_DATA'
export const ADMIN_PARKING_LOTS_SET_DATA = 'ADMIN_PARKING_LOTS_SET_DATA'

export const PROPERTY_COMPANIES_SET_DATA = 'PROPERTY_COMPANIES_SET_DATA'
export const OP_OPERATING_COMPANY_SET_DATA = 'OP_OPERATING_COMPANY_SET_DATA'
export const OP_USERS_SET_DATA = 'OP_USERS_SET_DATA'
export const OP_APP_ADVS_SET_DATA = 'OP_APP_ADVS_SET_DATA'
export const OP_DEVICE_ADVS_SET_DATA = 'OP_DEVICE_ADVS_SET_DATA'
export const OP_PARAMETER_SET_DATA = 'OP_PARAMETER_SET_DATA'

export const DISTRICTS_SET_DATA = 'DISTRICTS_SET_DATA'
export const PPC_USERS_SET_DATA = 'PPC_USERS_SET_DATA'
export const PPC_FEE_STANDARDS_SET_DATA = 'PPC_FEE_STANDARDS_SET_DATA'

export const BUILDINGS_SET_DATA = 'BUILDINGS_SET_DATA'